version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: '5672'
      RABBITMQ_QUEUE: 'tasks'
    volumes:
      - './index.js:/usr/src/app/index.js:ro'
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
    ports:
      - '${PORT:-8080}:15672'
      - '5672:5672'

volumes:
  rabbitmq_data: ~
